### PR TITLE
rename lighttpd-1.4.51 -> lighttpd-1.4.50

### PR DESCRIPTION
**Pull request by gstrauss**
A prior mistake labelled the lighttpd-1.4.50 release as lighttpd-1.4.51 in this repository.

This commit renames the directory, but to avoid breaking links, a symlink has been created from lighttpd-1.4.51 -> lighttpd-1.4.50.

The (renamed) lighttpd-1.4.50 directory contains lighttpd-1.4.50 source code plus two security patches backported from upstream lighttpd-1.4.51.

### CODE REVIEW

**Comment by anhu** [comment]
Contributor agreement is on file.

**Review by anhu — APPROVED** [review]

**Comment by gstrauss** [comment]
@julek-wolfssl: @anhu review this a week ago.  What are the next steps here?  Thanks.

**Comment by julek-wolfssl** [comment]
Hi @gstrauss, the next step is for the general reviewer to review and merge this. Since they are currently busy with the upcoming release I will go ahead and merge it for them. Thank you for your contribution.

**Comment by gstrauss** [comment]
Thanks, @julek-wolfssl!

**Pull request merged**
