### PR TITLE
Add libimobiledevice patches

### PR DESCRIPTION
**Pull request by julek-wolfssl**

### CODE REVIEW

**Comment by julek-wolfssl** [comment]
This patch requires the changes in the https://github.com/wolfSSL/wolfssl/pull/4300 pull request for wolfSSL.

**Comment by lealem47** [comment]
Make errors out on master with : 
```
/usr/bin/ld: /home/lealem/test-dir/osp/install-dir/usr/lib/x86_64-linux-gnu/libusbmuxd.a(libusbmuxd.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/home/lealem/test-dir/osp/install-dir/usr/lib/x86_64-linux-gnu/libusbmuxd.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:503: recipe for target 'libimobiledevice.la' failed
make[2]: *** [libimobiledevice.la] Error 1
make[2]: Leaving directory '/home/lealem/test-dir/osp/libimobiledevice-build/src'
Makefile:459: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lealem/test-dir/osp/libimobiledevice-build'
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2
```
Compiling with -fPIC and -no-pie yields the same error but I should mention it's building fine on my local machine. Could this have to do with the older version of gcc on master?

**Comment by haydenroche5** [comment]
Non-critical, but I'm getting these whitespace errors when applying the patch:

```
2018-09-03-fb71aeef10488ed7b0e60a1c8a553193301428c0.patch:60: trailing whitespace.
            
2018-09-03-fb71aeef10488ed7b0e60a1c8a553193301428c0.patch:93: trailing whitespace.
  
warning: 2 lines add whitespace errors.
```

Then, when I run `make`, I'm getting:

```
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
```

This is because pkg-config is finding openssl.pc on my system with the call to `PKG_CHECK_MODULES`. So, openssl_LIBS is getting defined to `-lssl -lcrypto`. One solution is to not call `PKG_CHECK_MODULES` for OpenSSL if using wolfSSL:

```
diff --git a/configure.ac b/configure.ac
index 7e8831d..1e8ec07 100644
--- a/configure.ac
+++ b/configure.ac
@@ -132,10 +132,11 @@ AC_ARG_ENABLE([openssl],
             
 if test "x$use_wolfssl" = "xyes"; then
   use_openssl=no
+else
+  pkg_req_openssl="openssl >= 0.9.8"
+  PKG_CHECK_MODULES(openssl, $pkg_req_openssl, have_openssl=yes, have_openssl=no)
 fi
 
-pkg_req_openssl="openssl >= 0.9.8"
-PKG_CHECK_MODULES(openssl, $pkg_req_openssl, have_openssl=yes, have_openssl=no)
 if test "x$have_openssl" = "xyes"; then
   if test "x$use_openssl" != "xyes"; then
     enable_openssl=no
```

After that change, everything compiles and links successfully for me.

**Comment by haydenroche5** [comment]
@lealem47, it looks like the build is attempting to use the static version of libusbmuxd, libusbmuxd.a. After I've built, if I run `ldd ./src/.libs/libimobiledevice.so`, I get the following output:

```
	linux-vdso.so.1 (0x00007ffc737b6000)
	libwolfssl.so.24 => /usr/local/lib/libwolfssl.so.24 (0x00007fc9b7df5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc9b7dd2000)
	libusbmuxd.so.6 => /usr/lib/x86_64-linux-gnu/libusbmuxd.so.6 (0x00007fc9b7dc5000)
	libplist.so.3 => /usr/lib/x86_64-linux-gnu/libplist.so.3 (0x00007fc9b7db4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc9b7bc2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc9b7a73000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9b7f59000)
```

Note that libusbmuxd is pointed at a share library, not a static one. Do you have a libusbmuxd.so rather than libusbmuxd.a installed? If not, that could be the problem.

**Comment by haydenroche5** [comment]
It looks like all these files include OpenSSL headers, but the patch isn't adding an include of wolfssl/options.h before them:

- userpref.c
- idevice.c
- idevice.h
- lockdown.c
- idevicebackup.c

**Comment by julek-wolfssl** [comment]
`wolfssl/options.h` is included by defining `EXTERNAL_OPTS_OPENVPN`. This way wolfSSL includes the options itself. Its something I've been abusing for quite a few ports so far because its so nice.

**Comment by haydenroche5** [comment]
> `wolfssl/options.h` is included by defining `EXTERNAL_OPTS_OPENVPN`. This way wolfSSL includes the options itself. Its something I've been abusing for quite a few ports so far because its so nice.

Thanks for pointing that out. Didn't notice before.

**Review by haydenroche5 — CHANGES_REQUESTED** [review]
Just my pkg-config comment and whitespace errors.

**Review by haydenroche5 — APPROVED** [review]
Looks and works great.

**Pull request merged**
