### PR TITLE
Adding files neccesary to build the freeradius-server port

### PR DESCRIPTION
**Pull request by lealem47**

### CODE REVIEW

**Review by ejohnstown — CHANGES_REQUESTED** [review]
Several of the files added to this repo are incidental files created by the configure and libtool scripts. Can you remove them from the PR, please?

**Comment by lealem47** [comment]
Unnecessary files have been removed

**Review by ejohnstown — CHANGES_REQUESTED** [review]
`missing` is also generated by configure.

**Comment by lealem47** [comment]
> `missing` is also generated by configure.

@ejohnstown I think my commit was removing `missing` from the repo, not adding it

**Comment by ejohnstown** [comment]
> > `missing` is also generated by configure.
> 
> @ejohnstown I think my commit was removing `missing` from the repo, not adding it

You are right. My error.

**Review by ejohnstown — APPROVED** [review]

**Pull request merged**
