### PR TITLE
Updating PPP to build with wolfSSL

### PR DESCRIPTION
**Pull request by lealem47**

### CODE REVIEW

**Review by ejohnstown — CHANGES_REQUESTED** [review]
There are several dozens of files that begin with a dot and are binary. I think what you checked in went through "zip" on a Mac where the extended file attributes were stored in the dot file. Can you purge them out of this PR?

**Comment by lealem47** [comment]
> There are several dozens of files that begin with a dot and are binary. I think what you checked in went through "zip" on a Mac where the extended file attributes were stored in the dot file. Can you purge them o

> There are several dozens of files that begin with a dot and are binary. I think what you checked in went through "zip" on a Mac where the extended file attributes were stored in the dot file. Can you purge them out of this PR?

They've been removed.

**Review by ejohnstown — CHANGES_REQUESTED** [review]
You missed a few. Try running `find ppp -name "._*"` from the osp directory.

**Comment by lealem47** [comment]
> You missed a few. Try running `find ppp -name "._*"` from the osp directory.

Ahh sorry about that. Should be gone now

**Review by ejohnstown — APPROVED** [review]

**Pull request merged**
